//! `FastIntWrite` trait — implemented by types that support a zero-overhead
//! integer-to-bytes fast path used by the `write!` / `writeln!` macros
//!
//! Author: aav

/// A write target that supports a fast decimal-integer path
///
/// Implemented by [`String`] and [`Vec<u8>`]. When the `write!` / `writeln!`
/// macros detect that their target implements this trait they bypass
/// `core::fmt` entirely and call `crate::fmt` directly, avoiding all format
/// string parsing overhead
pub trait FastIntWrite {
    /// Write the decimal ASCII representation of a `u64` into `self`
    fn write_u64_fast(&mut self, v: u64) -> Result<(), core::fmt::Error>;

    /// Write the decimal ASCII representation of a `u128` into `self`
    ///
    /// Default implementation routes through `vitoa::fmt_u128` and appends
    /// the resulting bytes
    fn write_u128_fast(&mut self, v: u128) -> Result<(), core::fmt::Error>;

    /// Append a newline byte (`b'\n'`)
    ///
    /// Used by the `writeln!` fast path after writing all integer arguments
    fn write_u64_fast_newline(&mut self) -> Result<(), core::fmt::Error>;
}

/// Sealed dispatch trait used by the `write!` / `writeln!` macros to route
/// every integer width to the correct `FastIntWrite` method without ever
/// performing a lossy `as u64` cast
///
/// Implemented for `u8`, `u16`, `u32`, `u64`, and `u128`. Not implemented
/// for signed integers or non-integer types — passing one of those to a
/// macro fast-path arm is a compile error rather than silent corruption
pub trait FastIntArg: sealed::Sealed {
    /// Forward `self` to the appropriate write method on `w`
    fn write_into<W: FastIntWrite + ?Sized>(self, w: &mut W) -> Result<(), core::fmt::Error>;
}

mod sealed {
    pub trait Sealed {}
}

// Trait impls for u8/u16/u32/u64 all route through `write_u64_fast` after a
// widening cast. Generated by a local macro to keep them in lockstep — adding a
// new sized integer is one line. u128 is the edge case (separate trait method).
macro_rules! impl_fast_int_arg_u64_cast {
    ($($t:ty),+ $(,)?) => {
        $(
            impl sealed::Sealed for $t {}
            impl FastIntArg for $t {
                #[inline]
                fn write_into<W: FastIntWrite + ?Sized>(self, w: &mut W) -> Result<(), core::fmt::Error> {
                    w.write_u64_fast(self as u64)
                }
            }
        )+
    };
}
impl_fast_int_arg_u64_cast!(u8, u16, u32, u64);

// u128: u64 can't hold the full value — route through the dedicated
// `write_u128_fast` method (implemented via `crate::fmt_u128`).
impl sealed::Sealed for u128 {}
impl FastIntArg for u128 {
    #[inline]
    fn write_into<W: FastIntWrite + ?Sized>(self, w: &mut W) -> Result<(), core::fmt::Error> {
        w.write_u128_fast(self)
    }
}

/// Blanket impl so callers can pass `&mut String` / `&mut Vec<u8>` directly
/// (which the macros do — the inner `let __w = &mut $w` produces a
/// `&mut &mut String` and we need [`FastIntWrite`] on the outer reference)
impl<T: FastIntWrite + ?Sized> FastIntWrite for &mut T {
    #[inline]
    fn write_u64_fast(&mut self, v: u64) -> Result<(), core::fmt::Error> {
        (**self).write_u64_fast(v)
    }
    #[inline]
    fn write_u128_fast(&mut self, v: u128) -> Result<(), core::fmt::Error> {
        (**self).write_u128_fast(v)
    }
    #[inline]
    fn write_u64_fast_newline(&mut self) -> Result<(), core::fmt::Error> {
        (**self).write_u64_fast_newline()
    }
}

/// Reserve `cap` bytes of spare in `vec`, hand `vitoa::fmt`-compatible logic
/// a `&mut [u8]` view over that spare region, then bump `len` by the count
/// the inner closure returns. Avoids the intermediate `[u8; N]` scratch +
/// `extend_from_slice` memcpy — the SIMD store lands directly in the
/// destination's heap buffer
///
/// # Arguments
///
/// * `vec`  - Target byte vector (the inner `Vec<u8>` for a `String` is fine
///   since `vitoa::fmt` only ever writes ASCII bytes)
/// * `cap`  - Bytes to reserve before the write (20 for u64, 40 for u128)
/// * `write` - Closure receiving the spare slice; returns the bytes written
///   or an `Err`
///
/// # Safety
///
/// The closure must write only valid UTF-8 bytes if `vec` is the backing of
/// a `String`, must not write more than `cap` bytes, and must return the
/// exact number of bytes it wrote
#[inline]
unsafe fn fill_spare<F>(vec: &mut Vec<u8>, cap: usize, write: F) -> Result<(), core::fmt::Error>
where
    F: FnOnce(&mut [u8]) -> Result<usize, crate::Error>,
{
    vec.reserve(cap);
    let len = vec.len();
    let capacity = vec.capacity();
    // SAFETY: reserve(cap) guarantees capacity - len >= cap; the spare slice
    // is fully owned by the Vec and not aliased.
    let spare =
        unsafe { core::slice::from_raw_parts_mut(vec.as_mut_ptr().add(len), capacity - len) };
    let n = write(spare).map_err(|_| core::fmt::Error)?;
    // SAFETY: caller's invariant — `write` wrote n bytes (n <= cap) of valid
    // UTF-8 (when vec backs a String) into spare[..n]. Bumping len to len+n
    // exposes those bytes as initialised.
    unsafe { vec.set_len(len + n) };
    Ok(())
}

impl FastIntWrite for String {
    #[inline]
    fn write_u64_fast(&mut self, v: u64) -> Result<(), core::fmt::Error> {
        // SAFETY: `vitoa::fmt` writes only ASCII decimal digits (b'0'..=b'9'),
        // which are valid 1-byte UTF-8 — String invariant preserved.
        unsafe { fill_spare(self.as_mut_vec(), 20, |spare| crate::fmt(v, spare)) }
    }

    #[inline]
    fn write_u128_fast(&mut self, v: u128) -> Result<(), core::fmt::Error> {
        // SAFETY: `vitoa::fmt_u128_inner` writes only ASCII decimal digits.
        unsafe {
            fill_spare(self.as_mut_vec(), 40, |spare| {
                crate::fmt_u128_inner(v, spare)
            })
        }
    }

    #[inline]
    fn write_u64_fast_newline(&mut self) -> Result<(), core::fmt::Error> {
        // SAFETY: b'\n' is valid single-byte UTF-8.
        unsafe { self.as_mut_vec().push(b'\n') };
        Ok(())
    }
}

impl FastIntWrite for Vec<u8> {
    #[inline]
    fn write_u64_fast(&mut self, v: u64) -> Result<(), core::fmt::Error> {
        // SAFETY: Vec<u8> has no UTF-8 invariant; `vitoa::fmt` writes exactly
        // n bytes of ASCII into the spare region.
        unsafe { fill_spare(self, 20, |spare| crate::fmt(v, spare)) }
    }

    #[inline]
    fn write_u128_fast(&mut self, v: u128) -> Result<(), core::fmt::Error> {
        // SAFETY: same as u64 case — n bytes of ASCII into spare.
        unsafe { fill_spare(self, 40, |spare| crate::fmt_u128_inner(v, spare)) }
    }

    #[inline]
    fn write_u64_fast_newline(&mut self) -> Result<(), core::fmt::Error> {
        self.push(b'\n');
        Ok(())
    }
}
